In [1]:
import numpy as np
import pandas as pd 
import heapq
import matplotlib.pyplot as plt

In [2]:
#Import Trainning set and Test Set.
df = pd.read_csv('spam_train.csv')
df.head()

,f1,f2,f3,f4,f5,f6,f7,f8,f9,f10,...,f49,f50,f51,f52,f53,f54,f55,f56,f57,class
0,0.00,0.64,0.64,0.0,0.32,0.00,0.00,0.00,0.00,0.00,...,0.00,0.000,0.0,0.778,0.000,0.000,3.756,61,278,1
1,0.21,0.28,0.50,0.0,0.14,0.28,0.21,0.07,0.00,0.94,...,0.00,0.132,0.0,0.372,0.180,0.048,5.114,101,1028,1
2,0.06,0.00,0.71,0.0,1.23,0.19,0.19,0.12,0.64,0.25,...,0.01,0.143,0.0,0.276,0.184,0.010,9.821,485,2259,1
3,0.00,0.00,0.00,0.0,0.63,0.00,0.31,0.63,0.31,0.63,...,0.00,0.137,0.0,0.137,0.000,0.000,3.537,40,191,1
4,0.00,0.00,0.00,0.0,0.63,0.00,0.31,0.63,0.31,0.63,...,0.00,0.135,0.0,0.135,0.000,0.000,3.537,40,191,1

In [3]:
#training set and test set 
X_train = df.drop('class',axis = 1 ).values
y_train = df['class']
target = df['class']

In [4]:
df2 = pd.read_csv('spam_test.csv')
df2.head()
X_test = df2.drop('Label',axis = 1 ).drop(' ID',axis = 1).values
y_test = df2['Label']
Label = list(df2['Label'])
k = [ 1, 5, 11, 21, 41, 61, 81, 101, 201, 401]

In [5]:
def z_score(X):
    x = X.T
    for i in range(len(x)):
        x[i] = (x[i]-x[i].mean())/x[i].std()
    return x.T

In [6]:
def score(ypred,testing):
    return (list(np.array(ypred) - np.array(testing)).count(0))/len(ypred)

In [7]:
def get_predict(final,cls,k_num):
    list_ = []
    for i in final:
        s = 0 
        for n in i :
            s += cls[n]
        if s*2 > k_num:
            yred = int(1)
        else:
            yred = int(0)
        list_.append(yred)
    return list_

In [8]:
def get_knn_predict(Xr,yr,Xt,yt,k_n,standard):
    Class = list(yr)
    Label = list(yt)
    yr = yr.values.reshape(-1,1)
    yt = yt.values.reshape(-1,1)
    if standard == True:
        xr = z_score(Xr)
        xt = z_score(Xt)
    else:
        xr = Xr.copy()
        xt = Xt.copy()
    Matrixdistance = []
    for j in range(len(xt)):
        listdistance = []
        outcome = []
        for u in range(len(xr)):
            distance = (((X_test[j]-X_train[u])**2).sum())**0.5
            listdistance.append(distance)
        Matrixdistance.append(listdistance)
    Database = pd.DataFrame(Matrixdistance) 
    list_acc = []
    for k in k_n:
        final_answer = []
        outcome = []
        y_pred = []
        for z in range(Database.shape[0]):
            list_distance = Database.iloc[z]
            target_distance = heapq.nsmallest(k,list_distance)
            min_num_index_list = list(map(list(list_distance).index, target_distance))
            final_answer.append(min_num_index_list)
        k_list = get_predict(final_answer,Class,k)
        acc = score(k_list,Label)
        list_acc.append(acc)
    return list_acc

In [9]:
#unstandardizing
get_knn_predict(X_train,y_train,X_test,y_test,k_n = k,standard=False)

[0.7522816166883963,
 0.7561929595827901,
 0.7640156453715776,
 0.7488048674489353,
 0.7540199913081269,
 0.738374619730552,
 0.7262059973924381,
 0.7288135593220338,
 0.7305519339417644,
 0.721425467188179]

In [10]:
#Standardizing
get_knn_predict(X_train,y_train,X_test,y_test,k_n = k,standard=True)

[0.8231203824424164,
 0.8309430682312038,
 0.8748370273794003,
 0.8700564971751412,
 0.8704910908300739,
 0.8700564971751412,
 0.8687527162103433,
 0.863102998696219,
 0.847457627118644,
 0.8144285093437635]